# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.box = "scotch/box"
    config.vm.network "private_network", ip: "192.168.33.10"
    config.vm.hostname = "pond-target-vm"

    config.vm.synced_folder "../app/src/php-deployer", "/var/php-deployer", :mount_options => ["dmode=777", "fmode=777"]
    config.vm.synced_folder ".", "/var/target-server-dev-environment", :mount_options => ["dmode=777", "fmode=777"]
end
